# Generated by Django 3.2.18 on 2023-04-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_class_litera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_class',
            field=models.IntegerField(default=10, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
