# Generated by Django 3.2.18 on 2023-04-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Group', verbose_name='Группы'),
        ),
    ]
