# Generated by Django 3.2.18 on 2023-04-06 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20230406_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='courses.course', verbose_name='Курс'),
        ),
    ]
