# Generated by Django 3.2.18 on 2023-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, default='2009-02-12', verbose_name='Дата урока'),
            preserve_default=False,
        ),
    ]
