# Generated by Django 3.2.18 on 2023-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='limit',
            field=models.IntegerField(blank=True, default=30, verbose_name='Лимит'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Открыт'),
        ),
    ]
