# Generated by Django 3.2.18 on 2023-04-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20230415_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.CharField(default='Нижний Новгород, Маринс Парк Отель', max_length=255, verbose_name='Место проведения'),
            preserve_default=False,
        ),
    ]
