# Generated by Django 3.2.18 on 2023-04-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='courses/documents/', verbose_name='Документ'),
        ),
    ]
