# Generated by Django 3.2.18 on 2023-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='courses/documents/applications/', verbose_name='Заполненный документ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='courses/documents/courses/', verbose_name='Документ'),
        ),
    ]
